spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: wonhee-bucket-files